const placeholderImage = "/assets/images/starter.jpg";

module.exports = {
    placeholderImage,
    sections: [
        {
            name: "Sharing Platters",
            slug: "sharing-platters",
            items: [
                {
                    name: "Prawn Cracker",
                    price: "£3.95",
                    description: "Let’s get you walking street nibbling!",
                    image: "/assets/images/dishes/Prawn Cracker.png",
                },
                {
                    name: "Aroy Thai Platter (Served 2)",
                    price: "£17.95",
                    description: "Thai Spring Rolls, Crispy Salt & Pepper Chicken, Chicken Satay & Crispy Fried Mushrooms",
                    image: placeholderImage,
                },
                {
                    name: "Bangkok Bites (Served 2)",
                    price: "£18.95",
                    description: "Crispy Fried Shredded Chicken Chili paste, Duck Spring Rolls, Crunchy Calamari and Prawns with Tamarind Sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Thai Seafood Duo – Som Tum Poo Nim & Tod Mun Talay (Served 2)",
                    price: "£20.95",
                    description: "Spicy Green Papaya Salad with Crispy Soft-Shell Crab & Thai Seafood Cakes Fresh green papaya salad tossed with chilli, lime, palm sugar and fish sauce, served with crispy soft-shell crab and Thai-style deep-fried seafood cakes.",
                    image: placeholderImage,
                },
                {
                    name: "Crispy Fried Chicken Chili Oil",
                    price: "£7.95",
                    description: "The best crispy shredded Chicken, made with fried chicken strips tossed with delicious chili oil, roasted white sesame seed.",
                    image: "/assets/images/dishes/Crispy Fried Shredded Chicken Chili Paste.png",
                },
                {
                    name: "Salt and Pepper Chicken",
                    price: "£7.95",
                    description: "Crispy tender chicken seasoned with salt and pepper served with Sriracha sauce.",
                    image: "/assets/images/dishes/Salt and Pepper Chicken.png",
                },
                {
                    name: "Chicken Thai Satay",
                    price: "£7.95",
                    description: "Chicken thigh satay served with traditional condiments, peanut sauce, and fluffy toast.",
                    image: "/assets/images/dishes/Chicken Thigh Satay.png",
                },
                {
                    name: "Hat Yai Fried Chicken (Gai Tod Hat Yai)",
                    price: "£7.95",
                    description: "Crispy Southern Thai-style fried chicken, served with crispy fried shallots and sweet chilli sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Larb Gai – Thai Spiced Chicken & Herb Salad",
                    price: "£7.95",
                    description: "Wok-tossed minced chicken with fresh herbs, fresh mint, red onion, chilli and toasted rice powder, finished with a vibrant lime and spicy Thai dressing.",
                    image: placeholderImage,
                },
                {
                    name: "Duck Spring Rolls",
                    price: "£8.50",
                    description: "A crispy spring roll wrapper encases duck breast and crunchy vegetables; A Hoisin sauce is the perfect complement on the side.",
                    image: "/assets/images/dishes/Duck Spring Rolls.png",
                },
                {
                    name: "Crunchy Calamari",
                    price: "£8.50",
                    description: "The squid is coated in batter and quickly deep fried to golden perfection. It is usually with a splash of salt and pepper, and Sriracha spicy dips.",
                    image: "/assets/images/dishes/Crunchy Calamari.png",
                },
                {
                    name: "Moo Dad Deaw – Thai-Style Sun-Dried Pork with Jaew dip",
                    price: "£8.95",
                    description: "Marinated pork, traditionally inspired by Thai Sun-drying, fried until tender with lightly crisp edges and served with a spicy, tangy Isaan-stryle Jaew dipping sauce",
                    image: placeholderImage,
                },
                {
                    name: "Pork Dumpling",
                    price: "£7.95",
                    description: "Steamed dumplings filled with tender pork and served with a gingery light soy and rice vinegar dipping.",
                    image: "/assets/images/dishes/Pork Dumpling.png",
                },
                {
                    name: "Crispy Fried Mushroom (V)",
                    price: "£6.95",
                    description: "These salt and pepper crunchy fried mushrooms are juicy on the inside and super crispy on the outside.",
                    image: "/assets/images/dishes/Crispy Fried Mushroom (V).png",
                },
                {
                    name: "Thai Sweet Corn Fritters (V)",
                    price: "£6.95",
                    description: "Thai corn fritters recipe (Tod Man Khao Pod) It’s a tasty finger food perfect for sharing as a tasty appetizer.",
                    image: "/assets/images/dishes/Thai Sweet Corn Fritters (V).png",
                },
                {
                    name: "Thai Spring Rolls (V)",
                    price: "£6.95",
                    description: "Thai vegetable spring rolls are crunchy and a crowd pleaser! The full flavour with sweet chili dipping.",
                    image: "/assets/images/dishes/Thai Spring Rolls (V).png",
                },
                {
                    name: "Tod Mun Talay (Thai Seafood Cakes)",
                    price: "£8.95",
                    description: "Traditional Thai-style deep-fried seafood cakes, made with a delicious blend of seafood, herbs and aromatic Thai spices. Crispy and golden on the outside, tender and flavourful inside, served with a sweet chilli dipping sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Crispy Chilli & Garlic Soft-Shell Crab",
                    price: "£8.95",
                    description: "Golden crispy soft-shell crab tossed with fresh chilli, garlic and spring onions.",
                    image: placeholderImage,
                },
                {
                    name: "Thai papaya Salad (Som Tum)",
                    price: "£8.95",
                    description: "Known as “Som Tam.” The salad combines crunchy strips of unripe green papaya with fresh chiles, pungent garlic, roasted peanuts, fine beans and tomatoes",
                    image: "/assets/images/dishes/Thai Papaya Salad (Som Tum).png",
                },
            ],
        },
        {
            name: "Soup",
            slug: "soup",
            items: [
                {
                    name: "Creamy Tom – Yum",
                    price: "Prawn £8.95 / Chicken £7.25 / Mushroom £6.95",
                    description: "Thai Tom Yum soup, full flavour such as lemongrass, lime, cream, onion, and chili combined with a stock base. Highly recommend!",
                    image: "/assets/images/dishes/Creamy Tom – Yum.png",
                },
                {
                    name: "Tom – Kha",
                    price: "Prawn £8.95 / Chicken £7.25 / Mushroom £6.95",
                    description: "Tom Kha!! this comforting Thai coconut soup is infused with the classic Thai herbs: lemongrass, galangal, and makrut (kaffir) lime leaves.",
                    image: "/assets/images/dishes/Tom – Kha.png.png",
                },
                {
                    name: "Seafood Hot & Sour Soup",
                    price: "£12.95",
                    description: "Traditional Thai clear sour soup known for its tangy, spicy, and fragrant profile.it is distinct for its reliance on ginger and a paste made from shallots, making it an intensely aromatic.",
                    image: placeholderImage,
                },
            ],
        },
        {
            name: "Thai Curry",
            slug: "thai-curry",
            items: [
                {
                    name: "Thai Panang Curry",
                    price: "Prawn £13.95 / Chicken £12.95 / Beef £12.95 / Vegetable & Tofu £11.95",
                    description: "Panang is one that is unique. Instead of having plenty of sauce that is creamy like Thai green curry, Panang comes in a small amount of curry thick and rich sauce.",
                    image: "/assets/images/dishes/Thai Panang Curry.png",
                },
                {
                    name: "Thai Red Curry",
                    price: "Prawn £13.95 / Chicken £12.95 / Beef £12.95 / Vegetable & Tofu £11.95",
                    description: "Aromatic blend of iconic Thai spices - red chillies, lemongrass, lime leaf and galangal - simmered in rich coconut milk. Fiery colour and slightly less spicy than Thai Green Curry.",
                    image: "/assets/images/dishes/Thai Red Curry.png",
                },
                {
                    name: "Thai Green Curry",
                    price: "Prawn £13.95 / Chicken £12.95 / Beef £12.95 / Vegetable & Tofu £11.95",
                    description: "Thai food is all about getting the right flavours. You want a good mix of sweet, sour, savoury, and spicy. This Thai green curry recipe will get the results that you’re looking for.",
                    image: "/assets/images/dishes/Thai Green Curry.png",
                },
                {
                    name: "Thai Massaman Curry",
                    price: "Prawn £13.95 / Chicken £12.95 / Beef £12.95 / Vegetable & Tofu £11.95",
                    description: "The bird’s eye chiles are a signature ingredient of curries from Thailand and turmeric gives it a yellow colour. The use of whole spices (coriander, cumin, and cardamom).",
                    image: "/assets/images/dishes/Thai Massaman Curry.png",
                },
            ],
        },
        {
            name: "Thai Stir-Fry",
            slug: "thai-stir-fry",
            items: [
                {
                    name: "Stir Fry Hot Thai Basil Leave",
                    price: "Prawn £13.95 / Chicken £12.95 / Beef £12.95 / Vegetable & Tofu £11.95",
                    description: "Thai basil leaves stir fry, well known in Thai as “Pad Gra-Pao”, is a contender for the most popular dish, and the most beloved Thai street food dish of all times.",
                    image: "/assets/images/dishes/Stir Fry Hot Thai Basil Leave.png",
                },
                {
                    name: "Stir fry Cashew Nuts",
                    price: "Prawn £13.95 / Chicken £12.95 / Beef £12.95 / Vegetable & Tofu £11.95",
                    description: "A classic Thai favourite stir fry (Pad Med Mamuang) the dish defined by its savory, slightly sweet and tangy sauce. It’s the perfect balance of textures, combining the softness of the meat and snap of nuts.",
                    image: "/assets/images/dishes/Stir Fry Cashew Nuts.png",
                },
                {
                    name: "Ginger Stir Fry",
                    price: "Prawn £13.95 / Chicken £12.95 / Beef £12.95 / Vegetable & Tofu £11.95",
                    description: "Fresh ginger in a flavour packed sauce tossed in a simple yet bold our homemade Thai stir fry sauce.",
                    image: "/assets/images/dishes/Ginger Stir Fry.png",
                },
                {
                    name: "Thai Sweet & Sour Sauce",
                    price: "Prawn £13.95 / Chicken £12.95 / Beef £12.95 / Vegetable & Tofu £11.95",
                    description: "A vibrant, tangy-sweet sauce with pineapple, tomato, and a delicate balance of sugar and vinegar.",
                    image: "/assets/images/dishes/Thai Sweet & Sour Sauce.png",
                },
                {
                    name: "Pad - Cha",
                    price: "Prawn £13.95 / Chicken £12.95 / Beef £12.95 / Vegetable & Tofu £11.95",
                    description: "Aromatic Thai stir-fry with your choice of meat, fresh peppercorns, chilli, garlic, Thai basil and fragrant herbs.",
                    image: placeholderImage,
                },
            ],
        },
        {
            name: "Beef & Lamb",
            slug: "beef-and-lamb",
            items: [
                {
                    name: "Surf & Turf",
                    price: "£20.95",
                    description: "A perfectly cooked sirloin and juicy marinated King Prawn, grilled to perfection on the barbecue, is a brilliant combo with Panang Curry Sauce.",
                    image: "/assets/images/dishes/Surf & Turf.png",
                },
                {
                    name: "Thai Holy Basil Sirloin",
                    price: "£18.95",
                    description: "Spicy Holy Basil Fried Rice. Their heat combined with the fragrance of Thai basil to tie it all together on top of fried rice and served accompanied with sunny egg and Grilled Sirloin steak.",
                    image: "/assets/images/dishes/Thai Holy Basil Beef Sirloin.png",
                },
                {
                    name: "Weeping Tiger",
                    price: "£18.95",
                    description: "E-San style (North-East of Thailand). Grilled Sirloin steak with a chilli and E-San herbs sauce. It’s perfectly married with the sweet, tart, and spicy Herbs served and Thai Pepper sauce.",
                    image: "/assets/images/dishes/Weeping Tiger.png",
                },
                {
                    name: "Grilled Sirloin Beef Yum (Yum Nua Yang)",
                    price: "£18.95",
                    description: "Tender grilled sirloin beef tossed with fresh herbs, red onion, tomatoes, chilli and lime in a spicy and tangy Thai dressing.",
                    image: placeholderImage,
                },
                {
                    name: "Slow Cooked Beef with Black Pepper",
                    price: "£18.95",
                    description: "Tender slow-cooked beef with fresh vegetables, garlic and cracked black pepper in a rich Thai-style savoury sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Slow Cook Beef Thai Massaman Curry",
                    price: "£18.95",
                    description: "Indulge in melt-in-your-mouth beef, slow-braised for many hours until tender, and submerged in a rice, velvety red curry sauce. Infused with the Massaman curry with coconut milk, potatoes and roasted cashew nuts. Gentle spiced with warm Thai aromatics.",
                    image: placeholderImage,
                },
                {
                    name: "Slow Cook Lamb Shank Massaman",
                    price: "£18.95",
                    description: "Lamb Massaman curry is a truly luxurious dish. Cooked in a Massaman sauce until meltingly tender and the spices blend so harmoniously with the lamb curry.",
                    image: "/assets/images/dishes/Slow-Cooked Lamb Shank Massaman.png",
                },
                {
                    name: "Slow Cook Lamb Cuts in Southern Thai Red Curry",
                    price: "£18.95",
                    description: "Slow braised for two hours until Lamb dice are soft and melting texture. Cooked with our homemade Southern Thai curry paste infused with the turmeric and dried chiles and a generous amount of black pepper.",
                    image: "/assets/images/dishes/Slow Cook Lamb Cuts in Southern Thai Red Curry.png",
                },
            ],
        },
        {
            name: "From The Sea",
            slug: "from-the-sea",
            items: [
                {
                    name: "Fishing Villages",
                    price: "£23.95",
                    description: "Whole sea bass, two giant king prawns, baby squid and mussels, flame-grilled top perfection and served with our vibrant Thai seafood dipping sauce, bursting with fresh lime, cilli, garlice and coriander.",
                    image: placeholderImage,
                },
                {
                    name: "Thai Tom – Yum Seafood Bouillabaisse",
                    price: "£23.95",
                    description: "Sea bass fillet, two giant king prawns, tender squid and mussels, gently cooked in a rich and aromatic Tom Yum broth, infused with lemongrass, galangal, kaffir lime and a touch of coconut milk.",
                    image: placeholderImage,
                },
                {
                    name: "Seafood Pad – Cha",
                    price: "£16.95",
                    description: "Hot and spicy stir-fried king prawns, mussels and squid a fiery PadCha sauce, a bold medicinal of fresh fingerroot (krachai), kaffir lime lives and Thai chilies.",
                    image: "/assets/images/dishes/Seafood Pad – Cha.png",
                },
                {
                    name: "Pan- Seared Cod Loin Pannang Curry",
                    price: "£18.95",
                    description: "Succulent cod loin, gently pan-seared and served with a rich, creamy Panang curry, infused with aromatic Thai spices, coconut milk and a hint of Kaffir lime.",
                    image: placeholderImage,
                },
                {
                    name: "Seared Cod Loin – Thai Basil & Roasted Pepper",
                    price: "£18.95",
                    description: "Pan-seared cod loin served with a rich roasted red pepper & Thai basil sauce, seasonal vegetables.",
                    image: placeholderImage,
                },
                {
                    name: "Grilled Salmon Green Thai Curry",
                    price: "£16.95",
                    description: "Perfectly seared salmon fillet, featuring a delicate, flaky texture and smoky char, served submerged in a vibrant and aromatic green curry sauce, crafted from fresh green chiles, coconut milk and fragrant Thai herbs.",
                    image: "/assets/images/dishes/Grilled Salmon Green Thai Curry.png",
                },
                {
                    name: "Pan – Seared Sea Bass Tom Kha Coconut Sauce",
                    price: "£16.95",
                    description: "Pan-seared sea bass fillet served in a fragrant Tom Kha coconut sauce, infused with lemongrass, galangal, kaffir lime, finish with fresh herbs and chilli oils.",
                    image: placeholderImage,
                },
                {
                    name: "Som- Tum Pla Yang",
                    price: "£19.95",
                    description: "Green Papaya Salad with whole grilled Sea Bass. Classic Thai green papaya salad with cherry tomatoes, green beans, chilli and lime and roasted pea nuts. Served with a whole sea bass grilled with aromantic lemongrass and kaffir lime leaves.",
                    image: placeholderImage,
                },
                {
                    name: "Chili & Lime Sea bass",
                    price: "£16.95",
                    description: "Sea bass steamed to perfection and dressed to impress with fresh Thai herbs and a fiery, chilies and lime sauce.",
                    image: "/assets/images/dishes/Chili & Lime Sea Bass.png",
                },
                {
                    name: "Grilled Mackerel ‘Miang Kham’",
                    price: "£16.95",
                    description: "Grilled mackerel served with rice vermicelli noodle, fresh vegetables, herbs and our homemade Thai hot and sour sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Giant King Prawns with Thai Curry Powder",
                    price: "£16.95",
                    description: "Giant king prawn’s wok-fried with aromatic curry powder, egg, onions, peppers and spring onions, fished in s rich and creamy Thai style sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Chu Chee Tiger Prawn",
                    price: "£16.95",
                    description: "Delicious Tiger prawns are cooking with our homemade basic red curry together with light coconut milk, giving a rich and thick texture flavours infused with lemongrass, galangal, coriander root, and kaffir lime.",
                    image: "/assets/images/dishes/Chu Chee Tiger Prawn.png",
                },
                {
                    name: "Tiger Prawn with Hot Thai Basil sauce",
                    price: "£18.95",
                    description: "Spicy Holy Basil Fried Rice. Their heat combined with the fragrance of Thai basil to tie it all together on top of fried rice and served accompanied with sunny egg and Grilled Tiger Prawns.",
                    image: "/assets/images/dishes/Tiger Prawn With Hot Thai Basil Sauce.png",
                },
            ],
        },
        {
            name: "Duck & Chicken",
            slug: "duck-and-chicken",
            items: [
                {
                    name: "Roasted Barbary Duck Red Curry",
                    price: "£18.95",
                    description: "Roasted Duck Curry, Red curry paste can go well together with coconut milk. Add crispy duck with sweet and sour pineapple, cherry tomato.",
                    image: "/assets/images/dishes/Roasted Barbary Duck Red Curry.png",
                },
                {
                    name: "Duck Stir Fry with Ginger Sauce",
                    price: "£18.95",
                    description: "Marinated duck breast with ginger stir fry sauce. The dish stir fried with a vegetable, mix pepper, broccoli, black fungus and spring onions.",
                    image: "/assets/images/dishes/Duck Stir Fry with Ginger Sauce.png",
                },
                {
                    name: "Honey Glazed Roast Barbary Duck",
                    price: "£18.95",
                    description: "Crispy and tender roasted duck with a little sweetness from the honey and orange and a hint of sweet chili sauce and fresh green peas.",
                    image: "/assets/images/dishes/Honey Glazed Roast Barbary Duck.png",
                },
                {
                    name: "Slow Braised Chicken Massaman",
                    price: "£16.95",
                    description: "Whole chicken leg slow-braised until tender in a rich, aromatic Massaman curry with creamy coconut milk, war Thai spices, roasted cashew nuts, fried shallots and potatoes.",
                    image: placeholderImage,
                },
                {
                    name: "Crispy Chicken with Thai Curry Powder",
                    price: "£16.95",
                    description: "Crispy fried chicken stir-fried with aromatic Thai Curry Powder, egg, onion, peppers and spring onion in rich, savoury curry sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Santa Chicken",
                    price: "£16.95",
                    description: "The best crispy shredded chicken tossed with delicious chili oil, roasted white sesame seed and top with green spring onion.",
                    image: "/assets/images/dishes/'Clacton Chicken'.png",
                },
            ],
        },
        {
            name: "Rice & Noodles",
            slug: "rice-and-noodles",
            items: [
                {
                    name: "Pad Thai",
                    price: "Prawn £13.95 / Chicken £12.95 / Beef £12.95 / Vegetable & Tofu £11.95",
                    description: "Indulge in Thailand’s most iconic noodle dish, featuring perfectly stir-fried rice noodles tossed in our signature tangy-sweet tamarind sauce.",
                    image: "/assets/images/dishes/Pad Thai.png",
                },
                {
                    name: "Kuaw Teow Pad Kra Pao",
                    price: "Prawn £13.95 / Chicken £12.95 / Beef £12.95 / Vegetable & Tofu £11.95",
                    description: "Stir-fried rice noodles with fresh Thai basil, chilli and garlic, with your choice of meat.",
                    image: placeholderImage,
                },
                {
                    name: "“Kee Mao” Rice Noodle",
                    price: "Prawn £13.95 / Chicken £12.95 / Beef £12.95 / Vegetable & Tofu £11.95",
                    description: "Authentic Kee Mao Rice Noodles, a bold and spicy stir-fry that is truly a labor of love. We toss wide, chewy rice noodles in high-heat wok with robust sauce of dark soy, garlic and fiery bird’s eye chilies.",
                    image: "/assets/images/dishes/Kee Mao_ Rice Noodle.png",
                },
                {
                    name: "Garlic Seafood Fried Rice",
                    price: "£14.95",
                    description: "Thai style fried rice with mixed seafood, egg and aromatic garlic.",
                    image: placeholderImage,
                },
                {
                    name: "Pineapple Fried Rice",
                    price: "£14.95",
                    description: "Taste buds to the tropics with our Pineapple Fried Rice, This vibrant dish features fragrant jasmine rice wok-tossed with cashew nuts, sweet pineapple chunks and a hint of aromatic curry powder. Top up with Thai chicken satay, tamarind-glazed prawns and Prawn crackers.",
                    image: "/assets/images/dishes/Pineapple Fried Rice.png",
                },
                {
                    name: "Giant Butterfly King Prawn Pad Thai",
                    price: "£16.95",
                    description: "The “Giant Kind Prawn” indulge in Thailand’s most iconic noodle dish, featuring perfectly stir-fried rice noodles tossed in our signature tangy-sweet tamarind sauce.",
                    image: "/assets/images/dishes/Giant Butterfly King Prawn Pad Thai.png",
                },
            ],
        },
        {
            name: "Goodies To Share",
            slug: "goodies-to-share",
            items: [
                {
                    name: "Garlic Steamed Noodles",
                    price: "£6.95",
                    description: "Delicious Thai noodles wok-fried with our homemade garlic and pepper stir fry sauce.",
                    image: "/assets/images/dishes/Garlic Steamed Noodles.png",
                },
                {
                    name: "Garlic Egg noodle",
                    price: "£6.95",
                    description: "Wok-tosses egg noodles with garlic and light soy sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Naan Bread",
                    price: "£4.95",
                    description: "Light, golden-brown Naan Bread - the perfect side for dipping up with Thai curries.",
                    image: "/assets/images/dishes/Naan Bread.png",
                },
                {
                    name: "Broccoli & Fine Bean",
                    price: "£6.95",
                    description: "Fresh greens stir-fried with crushed garlic and our homemade stir fry sauce, garnish.",
                    image: placeholderImage,
                },
                {
                    name: "Spicy Aubergine",
                    price: "£6.95",
                    description: "Chewy and soft Aubergine stir-fry with garlic, red chilli and soya bean paste, the delicious flavour to share.",
                    image: "/assets/images/dishes/Spicy Aubergine.png",
                },
            ],
        },
        {
            name: "Rice / Side Dishes",
            slug: "rice-side-dishes",
            items: [
                {
                    name: "Thai Jasmine Rice",
                    price: "£3.95",
                    description: "",
                    image: "/assets/images/dishes/Thai Jasmine Rice.png",
                },
                {
                    name: "Egg Fried Rice",
                    price: "£3.95",
                    description: "",
                    image: "/assets/images/dishes/Egg Fried Rice.png",
                },
                {
                    name: "Thai Coconut Rice",
                    price: "£3.95",
                    description: "",
                    image: "/assets/images/dishes/Thai Coconut Rice.png",
                },
                {
                    name: "Sticky Rice",
                    price: "£3.95",
                    description: "",
                    image: "/assets/images/dishes/Sticky Rice.png",
                },
            ],
        },
    ],
};