const placeholderImage = "/assets/images/starter.jpg";

module.exports = {
    placeholderImage,
    sections: [
        {
            name: "Sharing Platters",
            slug: "sharing-platters",
            items: [
                {
                    name: "Prawn Cracker",
                    price: "£3.65",
                    description: "Light crispy prawn crackers - the perfect start to your Thai feast.",
                    image: placeholderImage,
                },
                {
                    name: "Street Food Nibbles (Served 2)",
                    price: "£16.95",
                    description: "Thai spring roll, Crispy Chicken Thai Herbs, Chicken Thigh Satay and Crispy Fried Mushroom.",
                    image: placeholderImage,
                },
                {
                    name: "Delight Aroy Thai Platter (Served 2)",
                    price: "£18.95",
                    description: "Crispy Shredded Chicken, Duck Spring Rolls, Sea Bass Bites and Prawns with Tamarind Sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Clacton Platter (Served 2)",
                    price: "£20.95",
                    description: "Salt & Pepper Tiger Prawns, Calamari, Salt & Pepper Chicken and Papaya Salad with Sriracha dips.",
                    image: "/assets/images/dishes/Clacton Nibbles (Served 2).png",
                },
                {
                    name: "Crispy Fried Shredded Chicken Chili Paste",
                    price: "£6.95",
                    description: "Crispy shredded chicken strips tossed in chili oil with roasted white sesame seed.",
                    image: placeholderImage,
                },
                {
                    name: "Crispy Chicken Thai Herbs",
                    price: "£6.95",
                    description: "Chicken marinated in Thai spices and herbs, deep-fried until golden brown.",
                    image: placeholderImage,
                },
                {
                    name: "Salt and Pepper Chicken",
                    price: "£6.95",
                    description: "Crispy tender chicken seasoned with salt and pepper, served with Sriracha sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Chicken Thigh Satay",
                    price: "£7.25",
                    description: "Juicy chicken thigh satay with traditional condiments, peanut sauce and fluffy toast.",
                    image: "/assets/images/dishes/Chicken Thigh Satay.png",
                },
                {
                    name: "Duck Spring Rolls",
                    price: "£7.50",
                    description: "Crispy spring roll with duck breast and crunchy vegetables, served with Hoisin sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Crispy Salt & Pepper Tiger Prawns",
                    price: "£12.95",
                    description: "Deep-fried crispy tiger prawns tossed in salt, pepper and soy sauce with onions and peppers.",
                    image: placeholderImage,
                },
                {
                    name: "Crunchy Calamari",
                    price: "£7.50",
                    description: "Battered squid deep-fried to golden perfection, served with salt, pepper and Sriracha dip.",
                    image: placeholderImage,
                },
                {
                    name: "Pork Dumpling",
                    price: "£6.95",
                    description: "Steamed dumplings filled with tender pork, served with gingery soy and rice vinegar dip.",
                    image: placeholderImage,
                },
                {
                    name: "Crispy Fried Mushroom (V)",
                    price: "£5.95",
                    description: "Salt and pepper crunchy fried mushrooms - juicy inside and super crispy outside.",
                    image: placeholderImage,
                },
                {
                    name: "Thai Sweet Corn Fritters (V)",
                    price: "£5.95",
                    description: "Tod Man Khao Pod - lightly crisp golden corn fritters, perfect for sharing.",
                    image: placeholderImage,
                },
                {
                    name: "Thai Spring Rolls (V)",
                    price: "£5.95",
                    description: "Crunchy vegetable spring rolls served with sweet chilli dipping sauce.",
                    image: "/assets/images/dishes/Thai Spring Rolls (V).png",
                },
                {
                    name: "Crispy Sea Bass Bites",
                    price: "£12.95",
                    description: "Sea bass fillet marinated in Thai spices and herbs, deep-fried until golden brown.",
                    image: placeholderImage,
                },
                {
                    name: "Soft-Shell Crab",
                    price: "£12.95",
                    description: "Crispy whole soft-shell crab with chopped fresh chilli, garlic and spring onion.",
                    image: placeholderImage,
                },
                {
                    name: "Thai Papaya Salad (Som Tum)",
                    price: "£7.95",
                    description: "Crunchy unripe green papaya with fresh chiles, garlic, peanuts, fine beans and tomato.",
                    image: placeholderImage,
                },
            ],
        },
        {
            name: "Soup",
            slug: "soup",
            items: [
                {
                    name: "Creamy Tom - Yum",
                    price: "Prawn £7.95 / Chicken £7.25 / Mushroom £6.95",
                    description: "Thai Tom Yum soup with lemongrass, lime, cream, onion and chili in a rich stock base.",
                    image: placeholderImage,
                },
                {
                    name: "Tom - Kha",
                    price: "Prawn £7.95 / Chicken £7.25 / Mushroom £6.95",
                    description: "Comforting Thai coconut soup infused with lemongrass, galangal and kaffir lime leaves.",
                    image: "/assets/images/dishes/Tom – Kha.png",
                },
                {
                    name: "Seafood Hot & Sour Soup",
                    price: "£11.95",
                    description: "Traditional Thai clear sour soup with tangy, spicy and fragrant flavour from ginger and shallots.",
                    image: placeholderImage,
                },
            ],
        },
        {
            name: "Thai Curry",
            slug: "thai-curry",
            items: [
                {
                    name: "Thai Panang Curry",
                    price: "Prawn £12.95 / Chicken £11.95 / Beef £12.95 / Veg £10.95",
                    description: "Thick, rich and creamy curry with intense flavour - less watery than green curry.",
                    image: "/assets/images/dishes/Thai Panang Curry.png",
                },
                {
                    name: "Thai Red Curry",
                    price: "Prawn £12.95 / Chicken £11.95 / Beef £12.95 / Veg £10.95",
                    description: "Aromatic red chillies, lemongrass, lime leaf and galangal in rich coconut milk.",
                    image: "/assets/images/dishes/Thai Red Curry.png",
                },
                {
                    name: "Thai Green Curry",
                    price: "Prawn £12.95 / Chicken £11.95 / Beef £12.95 / Veg £10.95",
                    description: "The perfect mix of sweet, sour, savoury and spicy in a creamy green curry sauce.",
                    image: "/assets/images/dishes/Thai Green Curry.png",
                },
                {
                    name: "Thai Massaman Curry",
                    price: "Prawn £12.95 / Chicken £11.95 / Beef £12.95 / Veg £10.95",
                    description: "Bird's eye chiles, turmeric and whole spices - coriander, cumin and cardamom.",
                    image: "/assets/images/dishes/Thai Massaman Curry.png",
                },
                {
                    name: "Thai Yellow Curry",
                    price: "Prawn £12.95 / Chicken £11.95 / Beef £12.95 / Veg £10.95",
                    description: "Golden potatoes and carrot in rich coconut milk with homemade yellow curry paste.",
                    image: placeholderImage,
                },
            ],
        },
        {
            name: "Thai Stir-Fry",
            slug: "thai-stir-fry",
            items: [
                {
                    name: "Stir Fry Hot Thai Basil Leaves",
                    price: "Prawn £12.95 / Chicken £11.95 / Beef £12.95 / Veg £10.95",
                    description: "Pad GraPao - the most beloved Thai street food stir-fry dish of all times.",
                    image: "/assets/images/dishes/Stir Fry Hot Thai Basil Leave.png",
                },
                {
                    name: "Stir Fry Cashew Nuts",
                    price: "Prawn £12.95 / Chicken £11.95 / Beef £12.95 / Veg £10.95",
                    description: "Pad Med Mamuang - savory, slightly sweet and tangy with a perfect crunch of cashew nuts.",
                    image: "/assets/images/dishes/Stir Fry Cashew Nuts.png",
                },
                {
                    name: "Ginger Stir Fry",
                    price: "Prawn £12.95 / Chicken £11.95 / Beef £12.95 / Veg £10.95",
                    description: "Fresh ginger tossed in a flavour-packed, bold homemade Thai stir fry sauce.",
                    image: "/assets/images/dishes/Ginger Stir Fry.png",
                },
                {
                    name: "Thai Sweet & Sour Sauce",
                    price: "Prawn £12.95 / Chicken £11.95 / Beef £12.95 / Veg £10.95",
                    description: "Vibrant, tangy-sweet sauce with pineapple, tomato and a delicate balance of sugar and vinegar.",
                    image: "/assets/images/dishes/Thai Sweet & Sour Sauce.png",
                },
            ],
        },
        {
            name: "Beef & Lamb",
            slug: "beef-and-lamb",
            items: [
                {
                    name: "Surf & Turf",
                    price: "£20.95",
                    description: "Grilled sirloin and juicy marinated King Prawn on the barbecue with Panang Curry Sauce.",
                    image: "/assets/images/dishes/Surf & Turf.png",
                },
                {
                    name: "Thai Holy Basil Beef Sirloin",
                    price: "£18.95",
                    description: "Spicy Holy Basil Fried Rice topped with Grilled Sirloin steak and sunny egg.",
                    image: placeholderImage,
                },
                {
                    name: "Weeping Tiger",
                    price: "£18.95",
                    description: "E-San style Grilled Sirloin steak with chilli and E-San herbs sauce - sweet, tart and spicy.",
                    image: "/assets/images/dishes/Weeping Tiger.png",
                },
                {
                    name: "Slow-Cooked Beef Thai Red Curry",
                    price: "£16.95",
                    description: "Melt-in-your-mouth beef slow-braised in velvety red curry sauce with coconut milk.",
                    image: "/assets/images/dishes/beef-red-curry.jpg",
                },
                {
                    name: "Slow-Cooked Lamb Shank Massaman",
                    price: "£18.95",
                    description: "Meltingly tender lamb shank in a luxurious Massaman sauce with perfectly blended spices.",
                    image: "/assets/images/dishes/Slow-Cooked Lamb Shank Massaman.png",
                },
                {
                    name: "Slow Cook Lamb Cuts in Southern Thai Red Curry",
                    price: "£18.95",
                    description: "Slow-braised lamb dice in Southern Thai curry paste with turmeric, dried chiles and black pepper.",
                    image: "/assets/images/dishes/Slow Cook Lamb Cuts in Southern Thai Red Curry.png",
                },
            ],
        },
        {
            name: "From The Sea",
            slug: "from-the-sea",
            items: [
                {
                    name: "Grilled Mix Seafood",
                    price: "£20.95",
                    description: "Grilled Tiger Prawns, Calamari, Mussel and Sea Bass marinated in lemongrass with spicy sour sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Seafood Pad - Cha",
                    price: "£16.95",
                    description: "Spicy stir-fried king prawns, mussels and squid in fiery Pad-Cha sauce with krachai and Thai chilies.",
                    image: "/assets/images/dishes/Seafood Pad – Cha.png",
                },
                {
                    name: "Grilled Salmon Green Thai Curry",
                    price: "£17.95",
                    description: "Seared salmon fillet submerged in vibrant green curry sauce with coconut milk and Thai herbs.",
                    image: "/assets/images/dishes/Grilled Salmon Green Thai Curry.png",
                },
                {
                    name: "Grilled Salmon with Hot Thai Basil Sauce",
                    price: "£17.95",
                    description: "Golden-seared salmon fillet drizzled with fiery Pad Gra Pao with holy basil and bird's eye chilies.",
                    image: placeholderImage,
                },
                {
                    name: "Prawn & Soft-Shell Crab Southern Thai Red Curry",
                    price: "£18.95",
                    description: "Crispy soft-shell crab and prawns in spicy Southern Thai curry paste with turmeric and dried chiles.",
                    image: placeholderImage,
                },
                {
                    name: "Chili & Lime Sea Bass",
                    price: "£16.95",
                    description: "Sea bass steamed to perfection with fresh Thai herbs, fiery chili and lime sauce.",
                    image: "/assets/images/dishes/Chili & Lime Sea Bass.png",
                },
                {
                    name: "Chu Chee Tiger Prawn",
                    price: "£16.95",
                    description: "Tiger prawns in a rich red curry with light coconut milk, lemongrass, galangal and kaffir lime.",
                    image: "/assets/images/dishes/Chu Chee Tiger Prawn.png",
                },
                {
                    name: "Chu Chee Tiger Prawn (Holy Basil)",
                    price: "£16.95",
                    description: "Spicy Holy Basil Fried Rice topped with Crispy Tiger Prawns and sunny egg.",
                    image: "/assets/images/dishes/tiger-prawn-with-hot-thai-basil.jpg",
                },
            ],
        },
        {
            name: "Duck & Chicken",
            slug: "duck-and-chicken",
            items: [
                {
                    name: "Roasted Barbary Duck Red Curry",
                    price: "£18.95",
                    description: "Roasted duck in red curry with coconut milk, sweet and sour pineapple and cherry tomato.",
                    image: placeholderImage,
                },
                {
                    name: "Duck Stir Fry with Ginger Sauce",
                    price: "£18.95",
                    description: "Marinated duck breast stir-fried with ginger sauce, peppers, broccoli, black fungus and spring onions.",
                    image: "/assets/images/dishes/Duck Stir Fry with Ginger Sauce.png",
                },
                {
                    name: "Honey Glazed Roast Barbary Duck",
                    price: "£18.95",
                    description: "Crispy roasted duck glazed with honey and orange, finished with sweet chili sauce and green peas.",
                    image: "/assets/images/dishes/Honey Glazed Roast Barbary Duck.png",
                },
                {
                    name: "Duck with Hot Thai Basil Sauce",
                    price: "£18.95",
                    description: "Pad Gra-Pao Ped - succulent duck breast wok-tossed in holy basil, garlic and bird's eye chillis.",
                    image: placeholderImage,
                },
                {
                    name: "Aroy Thai Chicken Red Curry",
                    price: "£16.95",
                    description: "Grilled chicken breast sliced and bathed in smoky, creamy and aromatic red curry sauce.",
                    image: "/assets/images/dishes/_Aroy Thai Chicken Red Curry_.png",
                },
                {
                    name: "Clacton Chicken",
                    price: "£16.95",
                    description: "Crispy shredded chicken tossed in chili oil, roasted white sesame seed and spring onion.",
                    image: placeholderImage,
                },
                {
                    name: "Grilled Chicken Breast Black Bean Chili",
                    price: "£16.95",
                    description: "Thai-style grilled chicken in black bean sauce with peppers, onions and savoury stir-fry sauce.",
                    image: "/assets/images/dishes/Grilled Chicken Breast Black Bean Chili.png",
                },
                {
                    name: "Grilled Chicken Breast Pad - Cha",
                    price: "£16.95",
                    description: "Grilled chicken breast smothered in fiery Pad-Cha sauce with krachai and Thai chilies.",
                    image: placeholderImage,
                },
            ],
        },
        {
            name: "Rice & Noodles",
            slug: "rice-and-noodles",
            items: [
                {
                    name: "Pad Thai",
                    price: "Prawn £12.95 / Chicken £11.95 / Beef £12.95 / Veg £10.95",
                    description: "Thailand's most iconic noodle dish - stir-fried rice noodles in tangy-sweet tamarind sauce.",
                    image: "/assets/images/dishes/pad-thai.jpg",
                },
                {
                    name: "\"Kee Mao\" Rice Noodle",
                    price: "Prawn £12.95 / Chicken £11.95 / Beef £12.95 / Veg £10.95",
                    description: "Bold and spicy wide rice noodles wok-tossed in dark soy, garlic and fiery bird's eye chillies.",
                    image: placeholderImage,
                },
                {
                    name: "Pineapple Fried Rice",
                    price: "£13.95",
                    description: "Fragrant jasmine rice wok-tossed with chicken, prawn, sweet pineapple and a hint of curry powder.",
                    image: placeholderImage,
                },
                {
                    name: "Giant Butterfly King Prawn Pad Thai",
                    price: "£16.95",
                    description: "Pad Thai upgraded with Giant King Prawns in our signature tangy-sweet tamarind sauce.",
                    image: "/assets/images/dishes/Chicken Pad Thai.png",
                },
            ],
        },
        {
            name: "Goodies To Share",
            slug: "goodies-to-share",
            items: [
                {
                    name: "Garlic Steamed Noodles",
                    price: "£6.95",
                    description: "Thai noodles wok-fried with homemade garlic and pepper stir fry sauce.",
                    image: "/assets/images/dishes/Garlic Steamed Noodles.png",
                },
                {
                    name: "Naan Bread",
                    price: "£4.95",
                    description: "Light, golden-brown Naan Bread - the perfect side for dipping with Thai curries.",
                    image: "/assets/images/dishes/Naan Bread.png",
                },
                {
                    name: "Broccoli Stir-Fry",
                    price: "£6.95",
                    description: "Fresh greens stir-fried with crushed garlic and homemade stir fry sauce.",
                    image: placeholderImage,
                },
                {
                    name: "Spicy Aubergine",
                    price: "£6.95",
                    description: "Chewy and soft aubergine stir-fry with garlic, red chilli and soya bean paste.",
                    image: placeholderImage,
                },
            ],
        },
        {
            name: "Rice / Side Dishes",
            slug: "rice-side-dishes",
            items: [
                {
                    name: "Thai Jasmine Rice",
                    price: "£3.50",
                    description: "",
                    image: placeholderImage,
                },
                {
                    name: "Thai Coconut Rice",
                    price: "£3.95",
                    description: "",
                    image: "/assets/images/dishes/Thai Coconut Rice.png",
                },
                {
                    name: "Egg Fried Rice",
                    price: "£3.95",
                    description: "",
                    image: "/assets/images/dishes/Egg Fried Rice.png",
                },
                {
                    name: "Sticky Rice",
                    price: "£3.95",
                    description: "",
                    image: placeholderImage,
                },
            ],
        },
    ],
};
